frontend:
	sh components/frontend.sh

mongodb:
	sh components/mongodb.sh
	
catalogue:
	sh components/catalogue.sh
	
cart:
	sh components/cart.sh	

redis:
	sh components/redis.sh

user:
	sh components/user.sh

mysql:
	sh components/user.sh

shipping:
	sh components/user.sh

rabbitmq:
	sh components/user.sh

payment:
	sh components/user.sh

dispatch:
	sh components/user.sh